authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .forms import LoginForm
from . import views

app_name='authentication'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='authentication/login.html',authentication_form=LoginForm),name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('signup/',views.new_user,name='signup')
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('auth/',include('authentication.urls')),
    path('movies/',include('movies.urls')),
    path('movies/rooms/',include('conversationrooms.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversationrooms/urls.py
from django.urls import path

from . import views

app_name='conversationrooms'

urlpatterns = [
    path('<int:movie_id>/',views.rooms,name='rooms'),
    path('<int:movie_id>/new/',views.new_conversation_room,name='new'),
    path('<int:movie_id>/room/<int:room_pk>/',views.conversation_room,name='conversation_room')
]

core/urls.py
from django.urls import path

from . import views

app_name='core'

urlpatterns = [
    path('',views.index,name='index')
]

core/views.py
from django.shortcuts import render
from django.http import HttpResponse

from external_api.moviedb_api import moviedb

from movies.models import UserMovie
from conversationrooms.models import ConversationRoom

# Create your views here.

def index(request):
    try:
        top_movies=moviedb.get_top_movies(1)
    except:
        top_movies=[]

    top_movies_with_interactions=[{'top_movie':top_movie,
                                   'interactions':{'likes':UserMovie.objects.get_likes(top_movie['id']),'favorites':UserMovie.objects.get_favorites(top_movie['id'])},
                                   'rooms_count':ConversationRoom.objects.filter(movie_id=top_movie['id']).count()
                                   } for top_movie in top_movies]

    return render(request,'core/index.html',{
        'top_movies':top_movies_with_interactions,
    })

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{%endblock%} | Discuss Movie</title>
    <script src="https://unpkg.com/@tailwindcss/browser@4"></script>
</head>
<body>
    <div class="px-6 py-6 flex justify-between bg-slate-300 border-b border-slate-400">
        <a href="{%url 'core:index'%}" class="text-lg font-sans text-indigo">Discuss Movie</a>
        <div class="space-x-6">
            {% if request.user.is_authenticated %}
            <a href="{%url 'authentication:logout'%}" class="rounded-xl py-3 px-6 bg-cyan-500 text-white hover:bg-cyan-700">Logout</a>
            {% else %}
            <a href="{% url "authentication:login" %}" class="rounded-xl py-3 px-6 bg-cyan-500 text-white hover:bg-cyan-700">Login</a>
            <a href="{% url "authentication:signup" %}" class="rounded-xl py-3 px-6 bg-cyan-500 text-white hover:bg-cyan-700">Sign up</a>
            {% endif %}
        </div>
    </div>
    {%block content%}
    {%endblock%}

    <footer>
        <div class="py-10 justify-items-center bg-cyan-800 mt-10">
            <h3 class="text-white">Movie Discussion App</h3>
        </div>
    </footer>
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Welcome{% endblock title %}
{% block content %}
    <div>
        <h2 class="px-6 pt-6 text-indigo text-lg font-sans">Top Movies</h2>
        <div class="grid grid-cols-5 gap-3 mt-6 mx-6">
            {%for movie in top_movies%}
            <div >
                <a href="{%url 'conversationrooms:rooms' movie.top_movie.id%}">
                    <img class="rounded-t-xl" src="https://image.tmdb.org/t/p/w500/{{movie.top_movie.poster_path}}" alt="">
                    <div class="px-3 py-3 bg-gray-100 justify-items-center space-y-2 rounded-b-xl">
                        <h2>{{movie.top_movie.title}}</h2>
                        <p>{{movie.rooms_count}} rooms</p>
                        <div class="flex justify-between space-x-8">
                            <p class="inline-block">{{movie.interactions.likes}} likes</p>
                            <p class="inline-block">{{movie.interactions.favorites}} favorites</p>
                            <p class="inline-block">{{movie.top_movie.vote_average|floatformat:1}}</p>
                        </div>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>
{% endblock content %}