config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('auth/',include('authentication.urls')),
    path('movies/',include('movies.urls')),
    path('movies/rooms/',include('conversationrooms.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversationrooms/urls.py
from django.urls import path

from . import views

app_name='conversationrooms'

urlpatterns = [
    path('<int:movie_id>/',views.rooms,name='rooms'),
    path('<int:movie_id>/new/',views.new_conversation_room,name='new'),
    path('<int:movie_id>/room/<int:room_pk>/',views.conversation_room,name='conversation_room')
]

core/urls.py
from django.urls import path

from . import views

app_name='core'

urlpatterns = [
    path('',views.index,name='index')
]

movies/urls.py
from django.urls import path

from . import views

app_name='movies'

urlpatterns = [
    path('rooms/<int:movie_id>/like/',views.like,name='like'),
    path('rooms/<int:movie_id>/dislike/',views.dislike,name='dislike'),
    path('rooms/<int:movie_id>/favorite/',views.favorite,name='favorite')
]

conversationrooms/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ConversationRoom(models.Model):
    movie_id=models.IntegerField()
    room_name=models.TextField(default="Room 0")
    members=models.ManyToManyField(User,related_name='joined_conversation_rooms')
    created_by=models.ForeignKey(User,on_delete=models.CASCADE,related_name='created_conversation_rooms')
    created_at=models.DateField(auto_now_add=True)
    modified_at=models.DateField(auto_now=True)

    def save(self, *args, **kwargs):
        self.room_name = f"Room {ConversationRoom.objects.filter(movie_id=self.movie_id).count() + 1}"
        super().save(*args, **kwargs)

    class Meta:
        ordering=('-modified_at',)

class ConversationRoomMessage(models.Model):
    conversation_room=models.ForeignKey(ConversationRoom,on_delete=models.CASCADE,related_name='conversation_room_messages')
    member=models.ForeignKey(User,on_delete=models.CASCADE,related_name='sent_conversation_room_messages')
    content=models.TextField(max_length=300)
    created_at=models.DateField(auto_now_add=True)

conversationrooms/forms.py
from django import forms

from .models import ConversationRoomMessage
class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model=ConversationRoomMessage
        fields=('content',)
        widgets={
            'content':forms.TextInput(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }

conversationrooms/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required 

from .models import ConversationRoom,ConversationRoomMessage
from .forms import ConversationMessageForm

from external_api.moviedb_api import moviedb

from movies.models import UserMovie
from authentication.models import Profile


# Create your views here.

@login_required
def new_conversation_room(request,movie_id):
    conversation_room=ConversationRoom()
    conversation_room.movie_id=movie_id
    conversation_room.created_by=request.user
    conversation_room.save()
    conversation_room.members.add(request.user)

    return redirect('conversationrooms:rooms',movie_id)

def rooms(request,movie_id):
    movie=moviedb.get_movie_by_id(movie_id)
    user_movie=None
    if request.user.is_authenticated:
        user_movie=UserMovie.objects.get_or_none(movie_id=movie_id,user=request.user)

    likes=UserMovie.objects.get_likes(movie_id)
    dislikes=UserMovie.objects.get_dislikes(movie_id)
    favorites=UserMovie.objects.get_favorites(movie_id)

    is_like=user_movie.is_like if user_movie else None
    is_favorite=user_movie.is_favorite if user_movie else False

    movie_rooms=ConversationRoom.objects.filter(movie_id=movie_id)

    return render(request,'conversationrooms/movieconversationrooms.html',{
        'movie':movie,
        'movie_interactions':
        {
            'likes':likes,
            'dislikes':dislikes,
            'favorites':favorites
        },
        'user_interactions':{
            'is_like':is_like,
            'is_favorite':is_favorite,
        },
        'rooms':movie_rooms
    })

def conversation_room(request,room_pk,movie_id):
    conversation_messages=ConversationRoom.objects.get(pk=room_pk).conversation_room_messages.all()
    if request.method=="POST":
        form=ConversationMessageForm(request.POST)

        if form.is_valid():
            conversation_message=form.save(commit=False)
            conversation_message.conversation_room=ConversationRoom.objects.get(pk=room_pk)
            conversation_message.member=request.user

            conversation_message.save()
            return redirect('conversationrooms:conversation_room', movie_id=movie_id, room_pk=room_pk)
    
    else:
        form=ConversationMessageForm()


    return render(request,'conversationrooms/movieconversationroom.html',{
        'form':form,
        'conversation_messages':conversation_messages,
    })

conversationrooms/templates/conversationrooms/movieconversationroom.html
{% extends "core/base.html" %}
{% block title %}Movie Name Room{% endblock title %}
{% block content %}
    <div class="px-6 py-10">
        <div class="min-h-170">
            {%for message in conversation_messages%}
            <div class="flex items-center justify-center space-x-2 mb-5">
                {%if message.member != user%}
                <div class="inline-block"> 
                    <img class="rounded-full ring-1 ring-indigo-500 w-20 h-20"  src="{{message.member.profile.profile_image.url}}" alt="">
                </div>
                {%endif%}
                <div class="w-440 inline-block px-5 py-3 grid {%if message.member == user%} justify-items-end {%endif%} items-center bg-gray-200 rounded-xl">
                    <p class="text-sm text-gray-500 mb-2">{{message.member.username}}</p>
                    <p class="text-lg mb-2 text-black">{{message.content}}</p>
                </div>
                {%if message.member == user%}
                <div class="inline-block"> 
                    <img class="rounded-full ring-1 ring-indigo-500 w-20 h-20"  src="{{message.member.profile.profile_image.url}}" alt="">
                </div>
                {%endif%}
            </div>
            {%endfor%}
        </div>
        <div>
            <form action="." method="post">
                {%csrf_token%}
                {{form.as_p}}
    
                <div class="grid justify-items-end">
                    <input type="submit" value="Send" class="mt-5 py-3 px-8 text-lg bg-cyan-500 rounded-xl text-white hover:bg-cyan-700 cursor-pointer">
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

conversationrooms/templates/conversationrooms/movieconversationrooms.html
{% extends "core/base.html" %}
{% block title %}{{movie.title}}{% endblock title %}
{% block content %}
    <div class="px-6 py-6 flex space-x-7 items-center">
        <div >
            <h1 class="text-lg">{{movie.title}}</h1>
        </div>
        <div class="space-x-3 flex items-center">
            <div class="flex items-center space-x-1">
                <a href="{%url 'movies:like' movie.id%}">
                    {%if user_interactions.is_like == True%}
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-green-400 hover:text-green-700">
                        <path d="M7.493 18.5c-.425 0-.82-.236-.975-.632A7.48 7.48 0 0 1 6 15.125c0-1.75.599-3.358 1.602-4.634.151-.192.373-.309.6-.397.473-.183.89-.514 1.212-.924a9.042 9.042 0 0 1 2.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 0 0 .322-1.672V2.75A.75.75 0 0 1 15 2a2.25 2.25 0 0 1 2.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 0 1-2.649 7.521c-.388.482-.987.729-1.605.729H14.23c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 0 0-1.423-.23h-.777ZM2.331 10.727a11.969 11.969 0 0 0-.831 4.398 12 12 0 0 0 .52 3.507C2.28 19.482 3.105 20 3.994 20H4.9c.445 0 .72-.498.523-.898a8.963 8.963 0 0 1-.924-3.977c0-1.708.476-3.305 1.302-4.666.245-.403-.028-.959-.5-.959H4.25c-.832 0-1.612.453-1.918 1.227Z" />
                    </svg>
                    {%else%}
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-green-400 hover:text-green-700">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.633 10.25c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 0 1 2.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 0 0 .322-1.672V2.75a.75.75 0 0 1 .75-.75 2.25 2.25 0 0 1 2.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282m0 0h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 0 1-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 0 0-1.423-.23H5.904m10.598-9.75H14.25M5.904 18.5c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 0 1-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 9.953 4.167 9.5 5 9.5h1.053c.472 0 .745.556.5.96a8.958 8.958 0 0 0-1.302 4.665c0 1.194.232 2.333.654 3.375Z" />
                    </svg>
                    {%endif%}
                </a>
                <p class="text-base">{{movie_interactions.likes}}</p>    
            </div>
            <div class="flex items-center space-x-1">
                <a href="{%url 'movies:dislike' movie.id%}">
                    {%if user_interactions.is_like == False %}
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5 text-red-400 hover:text-red-700">
                        <path d="M15.73 5.5h1.035A7.465 7.465 0 0 1 18 9.625a7.465 7.465 0 0 1-1.235 4.125h-.148c-.806 0-1.534.446-2.031 1.08a9.04 9.04 0 0 1-2.861 2.4c-.723.384-1.35.956-1.653 1.715a4.499 4.499 0 0 0-.322 1.672v.633A.75.75 0 0 1 9 22a2.25 2.25 0 0 1-2.25-2.25c0-1.152.26-2.243.723-3.218.266-.558-.107-1.282-.725-1.282H3.622c-1.026 0-1.945-.694-2.054-1.715A12.137 12.137 0 0 1 1.5 12.25c0-2.848.992-5.464 2.649-7.521C4.537 4.247 5.136 4 5.754 4H9.77a4.5 4.5 0 0 1 1.423.23l3.114 1.04a4.5 4.5 0 0 0 1.423.23ZM21.669 14.023c.536-1.362.831-2.845.831-4.398 0-1.22-.182-2.398-.52-3.507-.26-.85-1.084-1.368-1.973-1.368H19.1c-.445 0-.72.498-.523.898.591 1.2.924 2.55.924 3.977a8.958 8.958 0 0 1-1.302 4.666c-.245.403.028.959.5.959h1.053c.832 0 1.612-.453 1.918-1.227Z" />
                    </svg>
                    {%else%}
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-red-400 hover:text-red-700">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M7.498 15.25H4.372c-1.026 0-1.945-.694-2.054-1.715a12.137 12.137 0 0 1-.068-1.285c0-2.848.992-5.464 2.649-7.521C5.287 4.247 5.886 4 6.504 4h4.016a4.5 4.5 0 0 1 1.423.23l3.114 1.04a4.5 4.5 0 0 0 1.423.23h1.294M7.498 15.25c.618 0 .991.724.725 1.282A7.471 7.471 0 0 0 7.5 19.75 2.25 2.25 0 0 0 9.75 22a.75.75 0 0 0 .75-.75v-.633c0-.573.11-1.14.322-1.672.304-.76.93-1.33 1.653-1.715a9.04 9.04 0 0 0 2.86-2.4c.498-.634 1.226-1.08 2.032-1.08h.384m-10.253 1.5H9.7m8.075-9.75c.01.05.027.1.05.148.593 1.2.925 2.55.925 3.977 0 1.487-.36 2.89-.999 4.125m.023-8.25c-.076-.365.183-.75.575-.75h.908c.889 0 1.713.518 1.972 1.368.339 1.11.521 2.287.521 3.507 0 1.553-.295 3.036-.831 4.398-.306.774-1.086 1.227-1.918 1.227h-1.053c-.472 0-.745-.556-.5-.96a8.95 8.95 0 0 0 .303-.54" />
                    </svg>
                    {%endif%}
                </a>
              <p class="text-base">{{movie_interactions.dislikes}}</p>    
            </div>
        </div>
        <div class="flex items-center space-x-1">
             <a href="{%url 'movies:favorite' movie.id%}">
                {%if user_interactions.is_favorite%}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5 text-red-400 hover:text-red-700">
                    <path d="m11.645 20.91-.007-.003-.022-.012a15.247 15.247 0 0 1-.383-.218 25.18 25.18 0 0 1-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0 1 12 5.052 5.5 5.5 0 0 1 16.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 0 1-4.244 3.17 15.247 15.247 0 0 1-.383.219l-.022.012-.007.004-.003.001a.752.752 0 0 1-.704 0l-.003-.001Z" />
                  </svg>
                {%else%}
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-red-400 hover:text-red-700">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
                </svg>
                {%endif%}
             </a>
             <p class="text-base">{{movie_interactions.favorites}}</p>    
        </div>
    </div>    
    <div>
        <div class="grid grid-cols-6 gap-3 mt-6 mx-6">
            {%for room in rooms%}
            <div>
                <a href="{%url 'conversationrooms:conversation_room' movie.id room.pk%}" class="inline-block">
                    <div class="w-70 h-110 bg-cyan-500 flex justify-center items-center rounded-xl hover:bg-cyan-700">
                        <p class="text-4xl text-white">{{room.room_name}}</p>
                    </div>
                </a>
            </div>
            {%endfor%}
            <div>
                <a href="{%url 'conversationrooms:new' movie.id%}" class="inline-block">
                    <div class="w-70 h-110 bg-cyan-500 flex justify-center items-center rounded-xl hover:bg-cyan-700">
                        <p class="text-9xl text-white">+</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
{% endblock content %}